# Generated by Django 4.0.5 on 2022-06-21 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='first_nam',
            new_name='first_name',
        ),
    ]
