# Generated by Django 4.0.5 on 2022-06-21 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_rename_first_nam_person_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='created_dat',
            new_name='created_date',
        ),
    ]
