# Generated by Django 4.0.5 on 2022-06-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_rename_created_dat_person_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(default='5999999', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
